x-n8n: &n8n-common
  image: n8nio/n8n:latest
  environment:
    N8N_PORT: 5678
    N8N_PROTOCOL: http
    N8N_HOST: localhost
    N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
    NODE_ENV: production
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
    N8N_RUNNERS_ENABLED: true
    WEBHOOK_URL: http://localhost:5678/
    
    SLACK_OAUTH_TOKEN: ${SLACK_OAUTH_TOKEN}
    SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}

services:
  n8n:
    <<: *n8n-common
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./shared:/data/shared
    depends_on:
      workflow-importer:
        condition: service_completed_successfully

  workflow-importer:
    <<: *n8n-common
    user: node
    entrypoint: /bin/sh
    command: [
      "-c",
      "if [ -d /backup/credentials ] && [ \"$(find /backup/credentials -type f | wc -l)\" -gt 0 ]; then n8n import:credentials --separate --input=/backup/credentials; fi && if [ -d /backup/workflows ] && [ \"$(find /backup/workflows -type f | wc -l)\" -gt 0 ]; then n8n import:workflow --separate --input=/backup/workflows; fi"
    ]
    volumes:
      - ./n8n/backup:/backup
    restart: "no"  # Run once and exit

volumes:
  n8n_data:
    driver: local